# Generated by Django 4.1 on 2022-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='qiymati',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
