# Generated by Django 4.1 on 2022-08-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_qiymati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='qiymati',
        ),
        migrations.AddField(
            model_name='post',
            name='daromadqiymati',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
